
server:
  port: 8080

spring:
  application:
    name: gateway-service
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        - id: crawler_route
          uri: lb://crawling-server
          predicates:
            - Path=/crawl/**
          filters:
            - RewritePath=/crawl/(?<segment>.*), /$\{segment} # URI ???
        - id: keyword_route
          uri: lb://keyword-server
          predicates:
            - Path=/keyword/**
          filters:
            - RewritePath=/keyword/(?<segment>.*), /$\{segment} # URI ???
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
