server:
  port: 8082
spring:
  application:
    name: keyword-server
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:./demo_dev;MODE=MYSQL
    username: keywordmaker
    password:
    driver-class-name: org.h2.Driver
  output:
    ansi:
      enabled: always





## Eureka Client
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
