server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/
  server:
    enable-self-preservation: true

spring:
  application:
    name: discovery-service